### ISSUE TITLE
How to get the file "open_train_**.json"

### ISSUE THREAD

**Issue by HUSTLyn** [HKUST-KnowComp/MLMET#2]
when I run `python trainweak.py 0` to pretrain a model with existing weak samples. An error is reported:
`FileNotFoundError: [Errno 2] No such file or directory: '/data/home/liyn/mlm_ufet_data/ultrafine/uf_data/total_train/open_train_00.json' `
Actually, in the Ultra-fine Entity Typing dataset, there is no folder called total_train

**Comment by hldai** [comment]
You need to ask the authors of Ultra-fine Entity Typing for the full training data.

**Comment by HUSTLyn** [comment]
> You need to ask the authors of Ultra-fine Entity Typing for the full training data.

Thanks! I will connect the authors.
