### ISSUE TITLE
Prediction of your model on the test set.

### ISSUE THREAD

**Issue by kosuke1701** [HKUST-KnowComp/MLMET#5]
Thanks for sharing code!
I want to compute different metrics (e.g. MRR) of the result reported in Table 3 of the paper. Would it be possible to share us predicted labels and scores of your model on the test set of the ultrafine entity typing dataset?

Best regards

**Comment by hldai** [comment]
Here is a trained model:

https://drive.google.com/file/d/1ofS3ayowcNaaRDBGvw3ClF_FNsYuzdLA/view?usp=sharing

**Comment by kosuke1701** [comment]
Thanks a lot! I will look into it.
